# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'collections_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowcol(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.createNew = QtWidgets.QPushButton(self.centralwidget)
        self.createNew.setGeometry(QtCore.QRect(570, 460, 171, 41))
        self.createNew.setObjectName("createNew")
        self.collectionName = QtWidgets.QLineEdit(self.centralwidget)
        self.collectionName.setGeometry(QtCore.QRect(30, 60, 251, 31))
        self.collectionName.setObjectName("collectionName")
        self.collectionLabel = QtWidgets.QLabel(self.centralwidget)
        self.collectionLabel.setGeometry(QtCore.QRect(30, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.collectionLabel.setFont(font)
        self.collectionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.collectionLabel.setObjectName("collectionLabel")
        self.translation = QtWidgets.QLineEdit(self.centralwidget)
        self.translation.setGeometry(QtCore.QRect(480, 260, 251, 31))
        self.translation.setObjectName("translation")
        self.word = QtWidgets.QLineEdit(self.centralwidget)
        self.word.setGeometry(QtCore.QRect(60, 260, 251, 31))
        self.word.setObjectName("word")
        self.wordLabel = QtWidgets.QLabel(self.centralwidget)
        self.wordLabel.setGeometry(QtCore.QRect(60, 190, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wordLabel.setFont(font)
        self.wordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wordLabel.setObjectName("wordLabel")
        self.TranslationLabel = QtWidgets.QLabel(self.centralwidget)
        self.TranslationLabel.setGeometry(QtCore.QRect(480, 190, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TranslationLabel.setFont(font)
        self.TranslationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TranslationLabel.setObjectName("TranslationLabel")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(320, 310, 161, 41))
        self.addButton.setObjectName("addButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 495, 450, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Новая коллекция"))
        self.createNew.setText(_translate("MainWindow", "Создать новую коллекцию"))
        self.collectionLabel.setText(_translate("MainWindow", "Название коллекции"))
        self.wordLabel.setText(_translate("MainWindow", "Новое слово"))
        self.TranslationLabel.setText(_translate("MainWindow", "Перевод"))
        self.addButton.setText(_translate("MainWindow", "Добавить в коллекцию"))
        self.label.setText(_translate("MainWindow", ""))
